PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS customers(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS session_customer ON sessions(customer_id);
CREATE TABLE IF NOT EXISTS cart(customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,color TEXT NOT NULL CHECK(color IN ('blue','pink','green')),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 99),PRIMARY KEY(customer_id,color));
CREATE TABLE IF NOT EXISTS addresses(customer_id TEXT PRIMARY KEY REFERENCES customers(id) ON DELETE CASCADE,name TEXT NOT NULL,street TEXT NOT NULL,line2 TEXT NOT NULL,city TEXT NOT NULL,state TEXT NOT NULL,zip TEXT NOT NULL,phone TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
