const PAGE_ROUTES = [
  { path: "/", key: "home" },
  { path: "/stocks", key: "stocks" },
  { path: "/stocks/bank-cards", key: "stocks-bank-cards" },
  { path: "/stocks/brokers", key: "stocks-brokers" },
  { path: "/stocks/bank-funding", key: "stocks-bank-funding" },
  { path: "/stocks/broker-funding", key: "stocks-broker-funding" },
  { path: "/stocks/withdrawal", key: "stocks-withdrawal" },
  { path: "/stocks/spending", key: "stocks-spending" },
  { path: "/crypto", key: "crypto" },
  { path: "/crypto/accounts", key: "crypto-accounts" },
  { path: "/crypto/funding", key: "crypto-funding" },
  { path: "/crypto/withdrawal", key: "crypto-withdrawal" },
  { path: "/crypto/spending", key: "crypto-spending" },
  { path: "/crypto/onchain", key: "crypto-onchain" },
  { path: "/crypto/onchain-us-stocks", key: "crypto-onchain-us-stocks" },
  { path: "/sim", key: "sim" },
  { path: "/sim/hk", key: "sim-hk" },
  { path: "/sim/us", key: "sim-us" },
  { path: "/portfolio", key: "portfolio" },
  { path: "/portfolio/transactions", key: "portfolio-transactions" },
  { path: "/portfolio/history", key: "portfolio-history" },
  { path: "/portfolio/realized-pnl", key: "portfolio-realized-pnl" },
  { path: "/portfolio/review", key: "portfolio-review" },
];

const LEGACY_REDIRECTS = {
  "/index.html": "/",
  "/offshore": "/",
  "/offshore/stocks": "/stocks",
  "/offshore/stocks/bank-cards": "/stocks/bank-cards",
  "/offshore/stocks/brokers": "/stocks/brokers",
  "/offshore/stocks/bank-funding": "/stocks/bank-funding",
  "/offshore/stocks/broker-funding": "/stocks/broker-funding",
  "/offshore/stocks/withdrawal": "/stocks/withdrawal",
  "/offshore/stocks/spending": "/stocks/spending",
  "/offshore/crypto": "/crypto",
  "/offshore/crypto/accounts": "/crypto/accounts",
  "/offshore/crypto/funding": "/crypto/funding",
  "/offshore/crypto/withdrawal": "/crypto/withdrawal",
  "/offshore/crypto/spending": "/crypto/spending",
  "/offshore/crypto/onchain": "/crypto/onchain",
  "/offshore/crypto/onchain-us-stocks": "/crypto/onchain-us-stocks",
  "/stocks/accounts": "/stocks/bank-cards",
  "/stocks/allocation": "/stocks/brokers",
  "/stocks/monitoring": "/stocks/broker-funding",
  "/crypto/fiat": "/crypto/funding",
  "/crypto/wallets": "/crypto/accounts",
  "/stocks.html": "/stocks",
  "/stocks-accounts.html": "/stocks/bank-cards",
  "/stocks-allocation.html": "/stocks/brokers",
  "/stocks-monitoring.html": "/stocks/broker-funding",
  "/crypto.html": "/crypto",
  "/crypto-fiat.html": "/crypto/funding",
  "/crypto-wallets.html": "/crypto/accounts",
  "/crypto-onchain.html": "/crypto/onchain",
  "/portfolio.html": "/portfolio",
};

module.exports = {
  PAGE_ROUTES,
  LEGACY_REDIRECTS,
};
