import {scrypt,randomBytes,timingSafeEqual,createHash} from 'node:crypto';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hash=x=>createHash('sha256').update(x).digest('hex');
const rand=()=>randomBytes(32).toString('hex');
const colors={blue:'Blue',pink:'Pink',green:'Lime green'};
const states='AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');
const derive=(p,s)=>new Promise((resolve,reject)=>scrypt(p,s,64,{N:32768,r:8,p:3,maxmem:64*1024*1024},(e,k)=>e?reject(e):resolve(k)));
async function password(p){const s=rand();return s+':'+(await derive(p,s)).toString('hex')}
async function verify(p,h){const [s,k]=h.split(':');const actual=await derive(p,s);return timingSafeEqual(actual,Buffer.from(k,'hex'))}
const security={'Cache-Control':'no-store, private','Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; script-src 'none'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY'};
const footer=`<footer><div><a class="brand" href="/">Happy Pet Harbor /</a><p>Operated by RaeHouser Trading LLC</p></div><nav aria-label="Footer navigation"><a href="/terms/">Terms</a><a href="/shipping/">Shipping</a><a href="/payment/">Payment &amp; billing</a><a href="/returns/">Returns &amp; refunds</a><a href="/privacy/">Privacy</a><a href="/contact/">Support</a></nav></footer>`;
function page(title,body,status=200,cookie){const h={...security};if(cookie)h['Set-Cookie']=cookie;return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${esc(title)} | Happy Pet Harbor</title><link rel="stylesheet" href="/style.css"><link rel="icon" href="/favicon.svg"></head><body><div class="preview">Pet leashes · $5.00 USD · Free shipping</div><header><a class="brand" href="/">Happy Pet Harbor /</a><nav aria-label="Main navigation"><a href="/products/padded-rope-leash/">Shop leash</a><a href="/account/">Account</a><a href="/cart/">Cart</a></nav></header><main class="shop-page"><h1>${esc(title)}</h1>${body}</main>${footer}</body></html>`,{status,headers:h})}
function redirect(path,cookie){const h={'Location':path,'Cache-Control':'no-store'};if(cookie)h['Set-Cookie']=cookie;return new Response(null,{status:303,headers:h})}
const cookie=t=>`__Host-hph_session=${t}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=1209600`;
const clear='__Host-hph_session=; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=0';
async function auth(req,env){const t=req.headers.get('Cookie')?.match(/(?:^|;\s*)__Host-hph_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!t)return null;return await env.DB.prepare('SELECT c.id,c.email,c.name,s.token FROM sessions s JOIN customers c ON c.id=s.customer_id WHERE s.token=? AND s.expires>?').bind(hash(t),Date.now()).first()}
async function session(env,id){const t=rand();await env.DB.prepare('INSERT INTO sessions(token,customer_id,expires) VALUES(?,?,?)').bind(hash(t),id,Date.now()+1209600000).run();return cookie(t)}
const validPassword=p=>typeof p==='string'&&p.length>=12&&p.length<=128;
const email=x=>String(x??'').trim().toLowerCase();
const pending=(c,q)=>colors[c]&&Number.isInteger(Number(q))&&Number(q)>=1&&Number(q)<=99?{color:c,quantity:Number(q)}:null;
const pendFields=p=>p?`<input type="hidden" name="color" value="${p.color}"><input type="hidden" name="quantity" value="${p.quantity}">`:'';
function login(p,msg=''){return `${msg?`<p class="shop-notice" role="alert">${esc(msg)}</p>`:''}${p?`<p>Sign in to add ${esc(colors[p.color])} × ${p.quantity} to your account cart.</p>`:''}<div class="auth-grid"><section><h2>Sign in</h2><form action="/account/login" method="post">${pendFields(p)}<label>Email<input name="email" type="email" autocomplete="username" required maxlength="254"></label><label>Password<input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><button class="button">Sign in</button></form></section><section><h2>Create an account</h2><form action="/account/register" method="post">${pendFields(p)}<label>Your name<input name="name" autocomplete="name" required maxlength="80"></label><label>Email<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>Password (12–128 characters)<input name="password" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><label>Confirm password<input name="confirm" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><label class="check-label"><input type="checkbox" name="terms" value="yes" required> I agree to the <a href="/terms/">terms and user agreement</a> and have read the <a href="/privacy/">privacy notice</a>.</label><button class="button">Create account</button></form></section></div><p class="secondary">Email verification and automated password reset are not available yet. Keep your password safe. If you need assistance, contact <a href="mailto:houserchiu@gmail.com">houserchiu@gmail.com</a>. Support cannot retrieve your password.</p>`}
async function limit(env,kind,key,max){const bucket=Math.floor(Date.now()/900000);const k=hash(kind+':'+key+':'+bucket);const r=await env.DB.prepare('INSERT INTO rate_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(k,Date.now()+900000).first();if(r.count>max)throw Object.assign(new Error('Too many attempts. Please try again in 15 minutes.'),{status:429})}
async function add(env,id,p){await env.DB.prepare('INSERT INTO cart(customer_id,color,quantity) VALUES(?,?,?) ON CONFLICT(customer_id,color) DO UPDATE SET quantity=MIN(99,cart.quantity+excluded.quantity)').bind(id,p.color,p.quantity).run()}
async function cart(env,id){return (await env.DB.prepare('SELECT color,quantity FROM cart WHERE customer_id=? ORDER BY color').bind(id).all()).results}
const csrfCheck=(req)=>{const u=new URL(req.url);if(req.headers.get('Origin')!==u.origin)throw Object.assign(new Error('This request could not be verified. Reload the page and try again.'),{status:403});if(!req.headers.get('Content-Type')?.startsWith('application/x-www-form-urlencoded'))throw Object.assign(new Error('Unsupported form.'),{status:415})};
const addressForm=a=>`<form action="/account/address" method="post"><label>Recipient name<input name="name" autocomplete="shipping name" maxlength="100" required value="${esc(a?.name)}"></label><label>Street address<input name="street" autocomplete="shipping address-line1" maxlength="160" required value="${esc(a?.street)}"></label><label>Apartment / suite (optional)<input name="line2" autocomplete="shipping address-line2" maxlength="100" value="${esc(a?.line2)}"></label><div class="field-row"><label>City<input name="city" autocomplete="shipping address-level2" maxlength="100" required value="${esc(a?.city)}"></label><label>State<select name="state" autocomplete="shipping address-level1" required><option value="">Select state</option>${states.map(s=>`<option ${a?.state===s?'selected':''} value="${s}">${s}</option>`).join('')}</select></label><label>ZIP code<input name="zip" autocomplete="shipping postal-code" pattern="[0-9]{5}(-[0-9]{4})?" maxlength="10" required value="${esc(a?.zip)}"></label></div><label>Phone (optional)<input name="phone" type="tel" autocomplete="shipping tel" maxlength="30" value="${esc(a?.phone)}"></label><p>Country: United States. Alaska, Hawaii and special addresses require delivery confirmation before purchase.</p><button class="button">Save address</button></form>${a?'<form action="/account/address/delete" method="post"><button class="text-button">Delete saved address</button></form>':''}`;
async function account(req,env,u){const a=await env.DB.prepare('SELECT * FROM addresses WHERE customer_id=?').bind(u.id).first();return page('Your account',`<p>Welcome, ${esc(u.name)}. ${esc(u.email)}</p><p>Your cart and saved address are linked to this account and available when you sign in on another device.</p><a class="button" href="/cart/">View cart</a><form action="/account/logout" method="post"><button class="text-button">Sign out</button></form>${new URL(req.url).searchParams.has('saved')?'<p class="shop-notice">Changes saved.</p>':''}<div class="auth-grid"><section><h2>Shipping address</h2>${addressForm(a)}</section><section><h2>Change password</h2><form action="/account/password" method="post"><label>Current password<input name="current" type="password" autocomplete="current-password" required maxlength="128"></label><label>New password (12–128 characters)<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></label><label>Confirm new password<input name="confirm" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></label><button class="button">Update password</button></form><p class="secondary">Changing your password signs you out on all devices. Email verification and automated password reset are not available yet.</p></section></div>`)}
async function cartPage(env,u){const rows=await cart(env,u.id);const total=rows.reduce((s,r)=>s+500*r.quantity,0);return page('Your cart',rows.length?`<p>Saved to your account.</p><div class="cart-list">${rows.map(r=>`<article class="cart-row"><img src="/assets/rope-leash-${r.color}.jpg" width="120" height="120" alt="${colors[r.color]} rope leash"><div><h2>Padded Handle Rope Leash</h2><p>${colors[r.color]} · 1.5 m · 1.0 cm · $5.00 USD each</p><form action="/cart/update" method="post"><input type="hidden" name="color" value="${r.color}"><label>Quantity<input type="number" min="1" max="99" name="quantity" value="${r.quantity}" required></label><button class="text-button">Update</button></form><form action="/cart/remove" method="post"><input type="hidden" name="color" value="${r.color}"><button class="text-button">Remove</button></form></div><strong>$${(r.quantity*5).toFixed(2)}</strong></article>`).join('')}</div><p class="cart-total">Product subtotal: $${(total/100).toFixed(2)} USD</p><p>Free standard shipping to the contiguous 48 states. Applicable taxes, availability and special-address delivery conditions are confirmed before purchase.</p><a class="button" href="/checkout/">Review delivery &amp; purchase</a>`:'<p>Your cart is empty.</p><a class="button" href="/products/padded-rope-leash/">Browse the leash</a>')}
async function checkout(env,u){const rows=await cart(env,u.id);const a=await env.DB.prepare('SELECT * FROM addresses WHERE customer_id=?').bind(u.id).first();if(!rows.length)return redirect('/cart/');const total=rows.reduce((s,r)=>s+5*r.quantity,0);return page('Review your purchase',`<h2>Items</h2><ul>${rows.map(r=>`<li>${colors[r.color]} rope leash × ${r.quantity} — $${(5*r.quantity).toFixed(2)} USD</li>`).join('')}</ul><p class="cart-total">Product subtotal: $${total.toFixed(2)} USD</p><h2>Shipping address</h2>${a?`<p>${esc(a.name)}<br>${esc(a.street)} ${esc(a.line2)}<br>${esc(a.city)}, ${esc(a.state)} ${esc(a.zip)}<br>United States</p>`:'<p>Save a shipping address in your account before proceeding.</p>'}<a class="text-link" href="/account/">${a?'Edit':'Add'} shipping address ↗</a><p>Processing: 1–3 business days after successful payment and confirmation. Estimated transit: 3–7 business days to the contiguous 48 states. Alaska, Hawaii and special addresses require confirmation.</p><p class="shop-notice">Online payment is not connected yet. No order or charge is created on this page. Contact us to confirm stock, any applicable tax and purchase arrangements.</p><a class="button" href="mailto:houserchiu@gmail.com?subject=Account%20cart%20purchase%20enquiry">Contact us about this cart ↗</a><p><a href="/payment/">Payment policy</a> · <a href="/shipping/">Shipping policy</a> · <a href="/returns/">Returns policy</a></p>`)}
export default {async scheduled(event,env){await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()),env.DB.prepare('DELETE FROM rate_limits WHERE expires<?').bind(Date.now())])},async fetch(req,env){const url=new URL(req.url);if(!/^\/(account|cart|checkout|shop)(\/|$)/.test(url.pathname))return env.ASSETS.fetch(req);try{
const route=url.pathname.replace(/\/$/,'');const u=await auth(req,env);
if(req.method==='GET'){if(route==='/account')return u?account(req,env,u):page('Sign in or create an account',login(pending(url.searchParams.get('color'),url.searchParams.get('quantity'))));if(route==='/cart')return u?cartPage(env,u):redirect('/account/');if(route==='/checkout')return u?checkout(env,u):redirect('/account/');return page('Page not found','<a href="/">Return to store</a>',404)}
if(req.method!=='POST')return page('Method not allowed','Please use the links in the store.',405);
csrfCheck(req);if(Number(req.headers.get('Content-Length')||0)>8192)return page('Request too large','Please shorten your input.',413);
const text=await req.text();if(text.length>8192)return page('Request too large','Please shorten your input.',413);const f=new URLSearchParams(text);const p=pending(f.get('color'),f.get('quantity'));const ip=req.headers.get('CF-Connecting-IP')||'local';
if(route==='/shop/add'){if(!p)return page('Invalid selection','Choose a color and a quantity from 1 to 99.',400);if(!u)return redirect(`/account/?color=${p.color}&quantity=${p.quantity}`);await add(env,u.id,p);return redirect('/cart/')}
if(route==='/account/register'||route==='/account/login'){
 await limit(env,'auth-ip',ip,20);const em=email(f.get('email'));await limit(env,'auth-email',em,10);const pw=f.get('password');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)||em.length>254||typeof pw!=='string'||pw.length>128)return page('Sign in or create an account',login(p,'Check your email and password.'),400);
 let c;
 if(route==='/account/register'){const name=(f.get('name')||'').trim();if(!validPassword(pw)||pw!==f.get('confirm')||!name||name.length>80||f.get('terms')!=='yes')return page('Sign in or create an account',login(p,'Use a 12–128 character password, confirm it, enter your name and agree to the terms.'),400);
 c={id:crypto.randomUUID()};const ph=await password(pw);try{await env.DB.prepare('INSERT INTO customers(id,email,name,password,created_at) VALUES(?,?,?,?,?)').bind(c.id,em,name,ph,Date.now()).run()}catch{return page('Sign in or create an account',login(p,'An account could not be created with these details. If you already registered, sign in.'),400)}
 }else{c=await env.DB.prepare('SELECT id,password FROM customers WHERE email=?').bind(em).first();const ok=await verify(pw,c?.password||('0'.repeat(64)+':'+ '0'.repeat(128)));if(!c||!ok)return page('Sign in or create an account',login(p,'Email or password is incorrect.'),401)}
 const ck=await session(env,c.id);if(p)await add(env,c.id,p);return redirect(p?'/cart/':'/account/',ck)
}
if(!u)return redirect('/account/');await limit(env,'action',u.id,100);
if(route==='/account/logout'){await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(u.token).run();return redirect('/account/',clear)}
if(route==='/cart/update'){if(!p)return page('Invalid quantity','Use a quantity from 1 to 99.',400);await env.DB.prepare('UPDATE cart SET quantity=? WHERE customer_id=? AND color=?').bind(p.quantity,u.id,p.color).run();return redirect('/cart/')}
if(route==='/cart/remove'){if(!colors[f.get('color')])return page('Invalid item','Choose an item in your cart.',400);await env.DB.prepare('DELETE FROM cart WHERE customer_id=? AND color=?').bind(u.id,f.get('color')).run();return redirect('/cart/')}
if(route==='/account/address/delete'){await env.DB.prepare('DELETE FROM addresses WHERE customer_id=?').bind(u.id).run();return redirect('/account/?saved=1')}
if(route==='/account/address'){const keys=['name','street','line2','city','state','zip','phone'];const a=Object.fromEntries(keys.map(k=>[k,(f.get(k)||'').trim()]));if(!a.name||a.name.length>100||!a.street||a.street.length>160||a.line2.length>100||!a.city||a.city.length>100||!states.includes(a.state)||!/^\d{5}(-\d{4})?$/.test(a.zip)||a.phone.length>30)return page('Check your address','<p>Enter a valid U.S. address and ZIP code.</p><a href="/account/">Return to your account</a>',400);await env.DB.prepare('INSERT INTO addresses(customer_id,name,street,line2,city,state,zip,phone) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(customer_id) DO UPDATE SET name=excluded.name,street=excluded.street,line2=excluded.line2,city=excluded.city,state=excluded.state,zip=excluded.zip,phone=excluded.phone').bind(u.id,...keys.map(k=>a[k])).run();return redirect('/account/?saved=1')}
if(route==='/account/password'){await limit(env,'password',u.id,5);const pw=f.get('password'),current=f.get('current');if(!validPassword(pw)||pw!==f.get('confirm')||typeof current!=='string'||current.length>128)return page('Check your password','<p>Use matching passwords of 12–128 characters.</p><a href="/account/">Return to account</a>',400);const row=await env.DB.prepare('SELECT password FROM customers WHERE id=?').bind(u.id).first();if(!await verify(current,row.password))return page('Check your password','<p>Current password is incorrect.</p><a href="/account/">Return to account</a>',400);const ph=await password(pw);await env.DB.batch([env.DB.prepare('UPDATE customers SET password=? WHERE id=?').bind(ph,u.id),env.DB.prepare('DELETE FROM sessions WHERE customer_id=?').bind(u.id)]);return redirect('/account/',clear)}
return page('Page not found','<a href="/">Return to store</a>',404)
}catch(e){if(e.status)return page('Please try again',`<p>${esc(e.message)}</p><a href="/account/">Return to your account</a>`,e.status);console.error('Shop request failed',e.name);return page('Temporarily unavailable','<p>Please try again shortly or contact houserchiu@gmail.com.</p>',503)}}};
